name: Python Tests for Joespy

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-18.04
    env:
      TOXENV: mypy
      GITHUB_WORKFLOW_URL:  https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      ID: ${{github.run_id}}
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: cache
        uses: actions/cache@v1
        id: cache
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-test
      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r constraints.txt
      - name: Run Tox
        run: tox -e py
      - name: Mattermost Hook       
        run: |
          echo "{\"text\":\"** :warning: certbot/josepy: Build failed :warning: ** | [(see details)]($GITHUB_WORKFLOW_URL) \"}" > mattermost.json
      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        if: ${{ success() }}
